export enum REGISTER{
        REGISTER_REQUEST = 'USERS_REGISTER_REQUEST',
        REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS',
        REGISTER_FAILURE = 'USERS_REGISTER_FAILURE'
    }


export enum LOGIN{
      LOGIN_REQUEST = 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE = 'USERS_LOGIN_FAILURE',
  }

export enum LOGOUT{
  LOGOUT = 'USERS_LOGOUT'
}

export type authConstantsType = REGISTER|LOGIN|LOGOUT
